### ISSUE TITLE
Support for AsciiDoc syntax 

### ISSUE THREAD

**Issue by eshepelyuk** [vmihalachi/turbo-editor#50]
Is it possible to add basic support for [AsciiDoctor](http://asciidoctor.org/) syntax ?

**Comment by hessianerd** [comment]
I would go one step further and ask for customizable syntax highlighting akin to notepad++'s user defined languages (http://npp-wiki.tuxfamily.org/index.php?title=User_Defined_Languages).  I work with a lot of esoteric "languages" that I would like to be able to use this, plus it would basically outsource the syntax highlighting to the users rather than the devs.  Lastly it would be the only editor on android with this feature.
